# Configure NTP servers based on list in all.yml
# ipspace Building Automation Solutions 2019
---
- hosts: csr
  connection: network_cli
  tasks:
  - name: "CONFIGURE NTP SERVERS"
    ios_config:
      lines: 
      - "ntp server {{ item }}"
    loop: "{{ ntp_servers }}"
    register: output
  - name: "SET FACT FOR ANSIBLE CHECK MODE"
    set_fact: 
      checkmode: "{{ansible_check_mode}}"
  - name: "CREATE DIR"
    file: path={{playbook_dir}}/results state=directory
    check_mode: no
  - name: "CREATE RESULT FILE WHEN IN CHECK MODE - OVERRIDE CHECK MODE TO EXECUTE TASK"
    copy: 
      content: |
        ******************************
        Results on {{inventory_hostname}}
        ******************************

        Device updated: {{result['changed']}}

        Attempted lines:
        {% for line in output['results'] %}
        {{ line['invocation']['module_args']['lines'][0] }}
        {% endfor %}
      dest: "{{playbook_dir}}/results/{{inventory_hostname}}.txt"
    check_mode: no
  - name: "COMPILE RESULTS INTO ONE FILE - OVERRIDE CHECK MODE TO EXECUTE TASK"
    assemble: src={{playbook_dir}}/results dest={{playbook_dir}}/results/results.txt
    run_once: true
#    when: checkmode
    check_mode: no
