# Gitlab CI config
---
stages:
  - yamllint
  - data model test

lint:
  stage: yamllint
  script:
    - bash validate-l3vpn/test/lint.sh

dm_test:
  stage: data model test
  script:
    - pytest
    #  - pytest -s -q validate-l3vpn/test/input_test.py
#    - bash validate-l3vpn/test/dm_test.sh
