# Gitlab CI config
---
stages:
  - yamllint
  - data model test

lint:
  stage: yamllint
  script:
    - bash lint.sh

dm_test:
  stage: data model test
  script:
    - cd validate-l3vpn/tests && pytest -s -q input_test.py -v
