# Gitlab CI config
---
stages:
  - yamllint
  - data model test
  - automation test

lint:
  stage: yamllint
  script:
    - bash validate-l3vpn/test/lint.sh

dm_test:
  stage: data model test
  script:
    - cd validate-l3vpn/test && pytest -s -q input_test.py
  only:
    - merge_request

auto_test:
  stage: automation test
  script:
    - cd validate-l3vpn/test && pytest -s -q input_test.py --scenario_fail_fabric_link
    - cd validate-l3vpn/test && pytest -s -q input_test.py --scenario_fail_fabric_node
    only:
    - merge_request