# Gather Facts Multi OS
---
- hosts: all
  connection: network_cli
  tasks:
  - name: "Gather Generic Facts"
    napalm_get_facts:
      hostname: '{{ansible_host}}'
      username: '{{ansible_user}}'
      dev_os: '{{ansible_network_os}}'
      password: '{{ ansible_ssh_pass }}'
    register: result
  - name: "NAPALM FACTS"
    debug:  
      var: result
