## Create Summary Report
# 
#
---
- name: "Read data"
  import_playbook: "get-l3vpn.yml"

- name: "Generate Report"
  hosts: pe2.pk.lab
  connection: network_cli
  # vars:
  # - results: "{{inventory_dir}}/results"
  tasks:
  # - name: "Offline print vars for debug"
  #   copy:
  #     content: "{{vars | to_nice_yaml(indent=4)}}"
  #     dest: "{{playbook_dir}}/results/vars.yml"
  - name: "Generate DOT file"
    template: src={{playbook_dir}}/templates/graph_vrf.j2 dest={{playbook_dir}}/results/{{inventory_hostname}}.dot
  - name: "Create image of DOT graph"
    shell: "dot -Tpng {{playbook_dir}}/results/{{inventory_hostname}}.dot > {{playbook_dir}}/results/{{inventory_hostname}}.png"
    run_once: true