## Create Summary Report
# 
#
---
- name: "Read data"
  import_playbook: "get-l3vpn.yml"

- name: "Generate Report"
  hosts: pe2.pk.lab
  connection: network_cli
  # vars:
  # - results: "{{inventory_dir}}/results"
  tasks:
  - name: "Generate DOT file"
    template: src={{playbook_dir}}/templates/graph_vrf.j2 dest={{playbook_dir}}/results/TEST.dot
       