---
- hosts: pe2.pk.lab
  connection: network_cli
  gather_facts: no
  vars_files:
    - l3vpn-properties.yml  
  roles:
    - ansible-pyats
  tasks:
    - name: Set local variables
      set_fact:
        router_id: "{{hostvars[inventory_hostname]['nodes']['pe'][inventory_hostname]['routerid']}}"
    - name: Run command to get VPNV4 data
      cli_command:
        command: sh ip bgp vpnv4 vrf {{l3vpn.0.name}}
      register: cli_output
    - name: Parsing output
      set_fact:
        rd_cli: "{{(l3vpn.0.type + ' RD ' + router_id + ':' + l3vpn.0.rd )}}"
        parsed_output: "{{ cli_output.stdout | pyats_parser('show ip bgp vpnv4 vrf {{l3vpn.0.name}}', 'iosxe') }}"
    - name: Set VPNV4 routes variable
      set_fact:
        routes: "{{parsed_output['vrf'][l3vpn.0.name]['address_family'][rd_cli]['routes']}}"

- hosts: ios_pe
  connection: network_cli
  gather_facts: no
  vars_files:
    - l3vpn-properties.yml
  roles:
    - ansible-pyats
  tasks:
    - name: Run command to get VRF BGP neighbor data
      cli_command:
        command: sh ip bgp vpnv4 vrf {{l3vpn.0.name}} neighbors
      register: cmd_output
    - name: Parsing BGP Neighbor output
      set_fact:
        bgp_neigh_output: "{{ cmd_output.stdout | pyats_parser('show ip bgp vpnv4 vrf {{l3vpn.0.name}} neighbors', 'iosxe') }}"