#
# Deploy eBGP peering for L3VPN
# This playbook is dependent on running 'create_data_model.yml' to produce 'nodes.yml'
---
- hosts: ios_pe
  connection: network_cli
  gather_facts: no
  vars_files:
    - nodes.yml
  tasks:
    - name: CREATE CONFIG DIRECTORY
      local_action: file path={{playbook_dir}}/results state=directory
      run_once: true
      check_mode: no
    - name: CREATE CONFIG
      template: src=./templates/l3vpn_service.j2 dest={{playbook_dir}}/results/{{inventory_hostname}}.bgp.cfg 