#
# Build base infrastructure configurations and services. 
# Deploy the full configuration to the nodes.
# 
# 
#
---
# - hosts: mpls
#   connection: network_cli
#   gather_facts: no
#   vars_files:
#     - nodes.yml
#     - services.yml
#   tasks:
#     - name: CREATE CONFIG DIRECTORY
#       local_action: file path={{playbook_dir}}/results state=directory
#       run_once: true
#       check_mode: no
#     - name: CREATE CONFIG
#       template: src=./templates/{{ansible_network_os}}-mpls-template.j2 dest={{playbook_dir}}/results/{{inventory_hostname}}_l3vpn.cfg
#     - name: CREATE DIFF FILES
#       local_action: file path={{playbook_dir}}/results/{{inventory_hostname}}.diff state=touch
#       check_mode: no
#     - name: DEPLOY CONFIG TO DEVICES
#       napalm_install_config:
#         hostname: "{{ inventory_hostname }}"
#         username: "{{ ansible_user }}"
#         dev_os: "{{ ansible_network_os }}"
#         password: "{{ ansible_ssh_pass }}"
#         config_file: "{{playbook_dir}}/results/{{inventory_hostname}}.cfg"
#         commit_changes: True
#         replace_config: True
#         get_diffs: True
#         diff_file: "{{playbook_dir}}/results/{{inventory_hostname}}.diff"
#       register: result
#     - name:  GET NAPALM FACTS 
#       napalm_get_facts:
#         hostname: "{{ansible_host}}"
#         username: "{{ansible_user}}"
#         dev_os: "{{ansible_network_os}}"
#         password: "{{ ansible_ssh_pass }}"
#         filter: ['facts', 'interfaces', 'interfaces_ip', 'bgp_neighbors']
#       register: napalm_facts
#     # - name: DEBUG VARIABLES 
#     #   copy:
#     #     content: "{{ vars | to_nice_yaml }}"
#     #     dest: "{{playbook_dir}}/facts.yml"
#     #   delegate_to: localhost
#     - name: CONFIGURATION DEPLOYMENT SUMMARY REPORT
#       template: src=./templates/deployment_summary.j2 dest={{playbook_dir}}/results/{{inventory_hostname}}_deployment_report.txt

- hosts: localhost
  gather_facts: no
  vars_files:
    - nodes.yml
    - services.yml
  tasks:
    - name: BUILD CPE INVENTORY
      include_role:
        name: cpe_router
    # - name: "CREATE SERVICE CPE NODE DATA MODEL"
    #   template: src=./templates/service_cpe_nodes.j2 dest=./cpe_nodes.yml

# - hosts: localhost
#   gather_facts: no
#   vars_files:
#     - nodes.yml
#     - services.yml
#   tasks:
#     - name: "CREATE FULL CPE CONFIGURATION"
#       template: src=./templates/nodes.j2 dest=./nodes.yml  