#
# These tasks retrieve and parse VRF names
#
---
- name: GET ALL VRF DATA FROM CLI
  cli_command:
    command: "show ip vrf detail"
  register: vrf_results
  tags: [step4, list_vrf]
- name: PARSE VRF INFO
  set_fact:
    parsed_vrf_stdout: "{{ vrf_results.stdout | pyats_parser('show ip vrf detail', 'iosxe') }}"
  tags: [step4, list_vrf]
- name: SET VRF VARIABLES
  set_fact:
    parsed_vrfs: "{{ parsed_vrf_stdout.keys() | list }}"
    node_vrfs: "{{ nodes[inventory_hostname]['vrfs'].keys() | list}}"
  tags: [step4, list_vrf] 
- name: REPORT VRF DIFF BETWEEN DATA MODEL AND EXISTING VRF
  blockinfile:
    create: yes
    path: "{{playbook_dir}}/results/reports/{{inventory_hostname}}.vrf"
    marker: "{mark}"
    marker_begin: "*** VRF REPORT: {{ lookup('pipe','date') }} "
    marker_end: "*** END\n"
    block: |
      NODE: {{ inventory_hostname }} 
      -------------------------
      EXISTING: (on the node)
      {% for vrf_name in parsed_vrfs %}
          {{ vrf_name }}
      {% endfor %}
      EXPECTED: (in service provisioning file)
      {% for node_vrf_name in node_vrfs %}
          {{ node_vrf_name }}
      {% endfor %}
      DIFF: 
          {{ parsed_vrfs | symmetric_difference(node_vrfs) }}
  tags: [step4, list_vrf]